plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "config/application.rb"
    - "config/initializers/devise.rb"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - "config/application.rb"